name: Dump firmware (full)

on:
  workflow_dispatch:
    inputs:
      ota:
        description: 'OTA'
        required: true

env:
  LD_LIBRARY_PATH: $GITHUB_WORKSPACE/bin

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup
      run: |
        sudo apt update
        sudo apt -y install zstd

    - name: Download
      id: download
      run: |
        curl -L ${{ inputs.ota }} -o ota.zip
        echo ::set-output name=ota_ver::`unzip -p ota.zip META-INF/com/android/metadata | grep ^version_name= | cut -b 14-`

    - name: Dump
      run: |
        unzip ota.zip payload.bin
        rm ota.zip
        mkdir ota
        ./bin/ota_extractor -output_dir ota -payload payload.bin
        pushd ota; for f in *; do zstd $f; done; popd

    - name: Upload release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: ota/*.img.zst
        artifactErrorsFailBuild: true
        body: ${{ inputs.ota }}
        tag: ${{ steps.download.outputs.ota_ver }}
        token: ${{ secrets.GITHUB_TOKEN }}
