name: Dump firmware (incremental)

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'URLs'
        required: true

env:
  LD_LIBRARY_PATH: $GITHUB_WORKSPACE/bin

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup
      run: |
        sudo apt update
        sudo apt -y install zstd

    - name: Dump
      id: dump
      run: echo ${{ inputs.urls }} | xargs ./dump_incremental.sh

    - name: Upload release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: ota/*.img.zst
        artifactErrorsFailBuild: true
        body: |
          ~ Incremental OTA ~
          ${{ steps.dump.outputs.body }}
        tag: ${{ steps.dump.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
